### ISSUE TITLE
A few dependencies and missing docker name

### ISSUE THREAD

**Issue by DanialOlsen** [Bohoaush/docker_build_caspar_Ub23#1]
I just had to run the docker with the following command (with the added --name):
docker run --name caspar-ub2204 -it caspar-ub2204 /bin/bash

And additionally these packages were missing for me:
apt install libsfml-graphics2.5 libglew2.2 libfreeimage3

After those changes it worked great for me. Thank you for this.

**Comment by Bohoaush** [comment]
Thank you! I completely forgot about adding the --name directive in the README. I also updated the readme with names of the packages you reported were missing in your install.
